#weights
weights: ./models/st_gcn.ntu-xview-p.pt
feeder: feeder.feeder.Feeder

test_feeder_args:
  #screw in_channels: 6
  data_path: ./data/NTU-RGB-D/xview-p/val_data.npy
  label_path: ./data/NTU-RGB-D/xview-p/val_label.pkl


# model
model: net.st_gcn.Model
model_args:
  in_channels: 6
  num_class: 60 
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:                                                                                     
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
              
phase: test
device: [2]
test_batch_size: 1

 