#weights: ./models/st_gcn.ntu-xview.pt

#ntu120-3
weights: ./models/st_gcn.ntu120all-csetup-3.pt
#ntu120-6
#weights: ./models/st_gcn.ntu120all-csetup-p.pt
model_fps: 30

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: ./data/NTU120all_org/csetup/val_data.npy
  label_path: ./data/NTU120all_org/csetup/val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  # in_channels: 6

  num_class: 120
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

# test 
phase: test
device: [7]
test_batch_size: 1

