work_dir: ./work_dir/recognition/ntu120all-csetup-p/ST_GCN


# ntu60 feeder
#feeder: feeder.feeder.Feeder
#train_feeder_args:
#  data_path: ./data/NTU-RGB-D/xview-p/train_data.npy
#  label_path: ./data/NTU-RGB-D/xview-p/train_label.pkl
#test_feeder_args:
#  data_path: ./data/NTU-RGB-D/xview-p/val_data.npy
#  label_path: ./data/NTU-RGB-D/xview-p/val_label.pkl


# ntu120 plucker
feeder: feeder.feeder.Feeder
# train_feeder_args:
#   data_path: ./data/NTU-RGB-D/xview120-p/train_data.npy
#   label_path: ./data/NTU-RGB-D/xview120-p/train_label.pkl
# test_feeder_args:
#   data_path: ./data/NTU-RGB-D/xview120-p/val_data.npy
#   label_path: ./data/NTU-RGB-D/xview120-p/val_label.pkl
train_feeder_args:
  data_path: ./data/NTU120all/csetup/train_screwdata.npy
  label_path: ./data/NTU120all/csetup/train_screwlabel.pkl
test_feeder_args:
  data_path: ./data/NTU120all/csetup/val_screwdata.npy
  label_path: ./data/NTU120all/csetup/val_screwlabel.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 6
  #ntu60
  #num_class: 60
  #ntu120
  num_class: 120
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [10, 50]

# training
device: [7]

batch_size: 1
test_batch_size: 1
# num_epoch: 80
num_epoch: 200



