weights: ./models/st_gcn.ntu-xview-3.pt
# weights: ./models/st_gcn.ntu-xview-p.pt
model_fps: 30

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  #ntu60
  #org in_channels: 3
  data_path: ./data/NTU-RGB-D/xview-3/val_data.npy
  label_path: ./data/NTU-RGB-D/xview-3/val_label.pkl
  #data_path: ./data/NTU-RGB-D/xsub/val_data.npy
  #label_path: ./data/NTU-RGB-D/xsub/val_label.pkl
  #screw in_channels: 6
  # data_path: ./data/NTU-RGB-D/xview-p/val_data.npy
  # label_path: ./data/NTU-RGB-D/xview-p/val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  # in_channels: 6

  num_class: 60
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

# test 
phase: test
device: [5]
test_batch_size: 1

