#weights: ./models/st_gcn.ntu-xsub.pt
# weights: ./models/st_gcn.ntu-xsub-p.pt
weights: ./models/st_gcn.ntu120all-csub-3.pt
model_fps: 30

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: ./data/NTU120all_org/csub/val_data.npy
  label_path: ./data/NTU120all_org/csub/val_label.pkl


# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  # in_channels: 6
  num_class: 120
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

# test 
phase: test
device: [5]
#device: [0]
test_batch_size: 1

