#ntu120
# weights

# weights: ./models/st_gcn.ntu120all-csub-p.pt
weights: ./models/st_gcn.ntu120all-csub-3.pt


# feeder
feeder: feeder.feeder.Feeder

test_feeder_args:
  #ntu120 org in_channels: 3
  data_path: ./data/NTU120all_org/csub/val_data.npy
  label_path: ./data/NTU120all_org/csub/val_label.pkl
  #ntu120 screw in_channels: 6
  # data_path: ./data/NTU120all/csub/val_screwdata.npy
  # label_path: ./data/NTU120all/csub/val_screwlabel.pkl
# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  # in_channels: 6
  num_class: 120
  
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

# test 
phase: test
# device: [0,1]
device: [4]
#device: [0,1,2,3,4,5]
test_batch_size: 1

